version: '3'

services:
  api:
    build: .
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; uvicorn main:app --host 0.0.0.0'
    container_name: nota-fastapi
    volumes:
      - .:/app
    restart: always
    ports:
      - 8000:8000
    environment:
      - DATABASE_URL=postgresql://admin:123456@db:5432/notaDB
    depends_on:
      - db

  db:
    image: postgres:15.1
    container_name: postgresDB
    restart: always
    expose:
      - 5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=notaDB
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
